Laura initial
ALMaclaine/photagallery pull request #1
Opened 2020-12-27 05:20 UTC by lauras5

- static page, loading images

2020-12-27 05:34 UTC, ALMaclaine requested changes

2020-12-27 05:34 UTC, ALMaclaine commented on src/static/images.mjs
> +    function imageComponent(img) {
no inner functions

2020-12-27 05:34 UTC, ALMaclaine commented on src/static/style.css
> +#loader {
dont style ids

2020-12-27 05:34 UTC, ALMaclaine commented on src/static/navbar.mjs
> +    navContainer.appendChild(nav_left);
add all created children together before adding to dom to prevent reflow, consider looking at document fragment if necessary

2020-12-27 05:34 UTC, ALMaclaine commented on src/static/images.mjs
> +    fetch('http://localhost:3000/api/image-metadata')
use async/await

2020-12-27 05:34 UTC, ALMaclaine commented on package.json
> +    "axios": "^0.21.1",
these are added to package json but aren't used anywhere in the commit

2020-12-27 05:34 UTC, ALMaclaine commented on package.json
> +    "form-data": "^3.0.0",
these are added to package json but aren't used anywhere in the commit

2020-12-27 07:50 UTC, lauras5 commented on package.json
> +    "form-data": "^3.0.0",
removed

2020-12-27 07:50 UTC, lauras5 commented on package.json
> +    "axios": "^0.21.1",
removed

2020-12-27 07:50 UTC, lauras5 commented on src/static/style.css
> +#loader {
changed to class

2020-12-27 22:33 UTC, ALMaclaine reviewed
delete dumb.rdb and add it to .gitignore

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/images.mjs
>          .then(response => response.json())
This is combining promise chaining (then) with async await, look into only using async/await.

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/images.mjs
> +                const imgCard = document.createElement('div');
using the imageComponent function was good, but defining it as an inner function was bad. move the function outside of the loadImages function. If you don't understand why ask me in our next call.

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/images.mjs
>          .catch(err => {
.catch is still promise chaining, look into how to properly use async/await

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/images.mjs
> +    loader.classList.add('loading--loading');
don't add classes that don't exist or serve some purpose in JS

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/index.html
> +<!--  <div id="navbar" class="navbar"></div>-->
don't leave dead code

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/index.html
>  <!--  <img src="http://localhost:3000/api/image?id=aslnasldkfnl&res=low"/>-->
don't leave dead code

2020-12-27 22:33 UTC, ALMaclaine commented on src/static/images.mjs
> -        imgDiv.dataset.id = img.id;
what is the purpose of adding the id to dataset?

2020-12-28 03:07 UTC, ALMaclaine requested changes

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/style.css
>  }
change body, html to

```css
body, html {
  height: 100%;
  font-family: sans-serif;
}

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +    imgDiv.src = imgURL;
inline if you don't use imgURL again.

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +    const response = await fetch('http://localhost:3000/api/image-metadata');
make api call relative `/api/image-metadata`

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +        images.map(e => imageContainer.append(imageComponent(e)));
Gather the imageComponents in a document fragment, then append the document fragment to imageContainer. That way you only have one reflow.

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +    fetchImages().catch(e => { console.log(e) });
use try catch

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +        loader.classList.add('loading--complete');
do we still need the loader? Maybe we just remove it from the document instead.

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +    const imgURL = `http://localhost:3000/api/image?id=${id}&res=low`
make api call relative `/api/image...`

2020-12-28 03:07 UTC, ALMaclaine commented on src/static/images.mjs
> +function imageComponent(img) {
you'll eventually need to rename this as we need several different images. low/med/full or search/preview/full

2020-12-28 04:15 UTC, ALMaclaine approved these changes
LGTM

2020-12-28 04:17 UTC, merged